# Generated by Django 4.1.7 on 2023-04-15 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0002_remove_establishments_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishments',
            name='category',
            field=models.CharField(choices=[('r', 'restaurant'), ('c', 'cafe'), ('p', 'bar')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='category',
            field=models.CharField(choices=[('sp', 'sport'), ('tr', 'traveling'), ('pt', 'painting'), ('cg', 'computer_games'), ('sh', 'shopping'), ('ph', 'photo'), ('ms', 'music')], max_length=2),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 4, 15, 17, 34, 17, 588712)),
        ),
    ]
