# Generated by Django 4.1.7 on 2023-04-30 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0007_alter_passport_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 4, 30, 16, 25, 8, 691309)),
        ),
        migrations.AddIndex(
            model_name='establishments',
            index=models.Index(fields=['name'], name='arrangement_name_39c02b_idx'),
        ),
        migrations.AddIndex(
            model_name='establishments',
            index=models.Index(fields=['-name'], name='arrangement_name_2cb422_idx'),
        ),
        migrations.AddIndex(
            model_name='establishments',
            index=models.Index(fields=['category'], name='arrangement_categor_6b5a37_idx'),
        ),
        migrations.AddIndex(
            model_name='establishments',
            index=models.Index(fields=['-category'], name='arrangement_categor_05d44e_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['min_bill_value'], name='arrangement_min_bil_fc65a0_idx'),
        ),
        migrations.AddIndex(
            model_name='hobbies',
            index=models.Index(fields=['name'], name='arrangement_name_ba33d1_idx'),
        ),
        migrations.AddIndex(
            model_name='hobbies',
            index=models.Index(fields=['-name'], name='arrangement_name_ddd198_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['max_spent_value'], name='arrangement_max_spe_30f636_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['name', 'age'], name='arrangement_name_3429c5_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['name'], name='arrangement_name_9dbcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['age'], name='arrangement_age_19c875_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['-name'], name='arrangement_name_4310b3_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['-age'], name='arrangement_age_e19a8b_idx'),
        ),
    ]
