# Generated by Django 4.1.7 on 2023-04-30 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0009_remove_establishments_arrangement_name_39c02b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 4, 30, 21, 1, 50, 39886)),
        ),
        migrations.AddIndex(
            model_name='establishments',
            index=models.Index(fields=['name'], name='arrangement_name_39c02b_idx'),
        ),
        migrations.AddIndex(
            model_name='establishments',
            index=models.Index(fields=['-name'], name='arrangement_name_2cb422_idx'),
        ),
        migrations.AddIndex(
            model_name='establishments',
            index=models.Index(fields=['category'], name='arrangement_categor_6b5a37_idx'),
        ),
        migrations.AddIndex(
            model_name='establishments',
            index=models.Index(fields=['-category'], name='arrangement_categor_05d44e_idx'),
        ),
    ]
