# Generated by Django 4.1.7 on 2023-05-20 09:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0010_alter_passport_date_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrangements',
            options={'verbose_name_plural': 'Свидания'},
        ),
        migrations.AlterModelOptions(
            name='establishments',
            options={'verbose_name_plural': 'Заведения'},
        ),
        migrations.AlterModelOptions(
            name='establishmentsrating',
            options={'verbose_name_plural': 'Рейтинг заведений'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name_plural': 'Гости'},
        ),
        migrations.AlterModelOptions(
            name='hobbies',
            options={'verbose_name_plural': 'Хобби'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name_plural': 'Приглашающие'},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name_plural': 'Паспорт'},
        ),
        migrations.AlterModelOptions(
            name='userrating',
            options={'verbose_name_plural': 'Рейтинг пользователей'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 5, 20, 12, 38, 18, 838786)),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='minimum age for registration is 18 years'), django.core.validators.MaxValueValidator(90, message='maximum age for registration is 90 years')]),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_created=datetime.datetime(2023, 5, 20, 12, 38, 18, 880777))),
                ('price', models.PositiveIntegerField()),
                ('arrangement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arrangement.arrangements')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.establishments')),
            ],
            options={
                'verbose_name_plural': 'Заказ',
            },
        ),
    ]
