# Generated by Django 4.1.7 on 2023-05-20 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0011_alter_arrangements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_photo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 5, 20, 23, 38, 27, 195455)),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 5, 20, 23, 38, 27, 164211)),
        ),
    ]
