# Generated by Django 4.1.7 on 2023-05-20 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0012_users_photo_alter_order_date_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishments',
            name='photo',
            field=models.ImageField(null=True, upload_to='establishment_photo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 5, 20, 23, 41, 55, 826336)),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 5, 20, 23, 41, 55, 779465)),
        ),
    ]
